MEUCANDIDATO:
  DEBUG: true
  RELOADER: true
  SECRET_KEY: 's3cret key'
  HOST: '0.0.0.0'
  PORT: 5000

  # Database
  DB_URI: 'mongodb://localhost:27017'
  DB_NAME: 'meucandidato'

  # Extensions
  EXTENSIONS:
    - meucandidato.ext.database.configure
    - meucandidato.ext.debug.configure
    - meucandidato.ext.homepage.configure

  # Flask Debug Toolbar
  DEBUG_TOOLBAR_ENABLED: true
  DEBUG_TB_INTERCEPT_REDIRECTS: false
  DEBUG_TB_PROFILER_ENABLED: true
  DEBUG_TB_TEMPLATE_EDITOR_ENABLED: true